version: "3"
services:
  nginx_symfony_training:
    container_name: nginx_symfony_training
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    networks:
      - symfonytraining

  symfony_training:
    container_name: symfony_training
    build:
      context: ./docker/php
      args:
        - DOCUMENT_ROOT=/var/www/html
        - UID=${UID}
    volumes:
      - ${SYMFONY_ROOT_DIRECTORY}:/var/www/html:cached
      - ./docker/php/settings/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - nginx_symfony_training
      - mysql_symfony_training
    environment:
      VIRTUAL_HOST: ${SYMFONY_VIRTUAL_HOST}
      XDEBUG_MODE: 1
    networks:
      symfonytraining:
        aliases:
          - ${SYMFONY_VIRTUAL_HOST}

  mysql_symfony_training:
    build:
      context: ./docker/mariaDB
    volumes:
      - ${DB_ROOT_DIRECTORY}:/var/lib/mysql
    container_name: mysql_symfony_training
    ports:
      - "${DATABASE_PORTS}"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
    expose:
      - 3306
    networks:
      - symfonytraining

networks:
  symfonytraining:
    driver: bridge
