# config/validator/validation.yaml
App\Form\Model\ProductDto:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
          max: 255
          minMessage: 'Name must be at least {{ limit }} characters long'
          maxMessage: 'Name cannot be longer than {{ limit }} characters'
          allowEmptyString: false
    description:
      - NotBlank: ~
      - Length:
          min: 10
          max: 255
          minMessage: 'Description must be at least {{ limit }} characters long'
          maxMessage: 'Description cannot be longer than {{ limit }} characters'
          allowEmptyString: false