# config/validator/validation.yaml
App\Form\Model\ProductDto:
  properties:
    title:
      - NotBlank: ~
      - Length:
          min: 3
          max: 255
          minMessage: 'Title must be at least {{ limit }} characters long'
          maxMessage: 'Title cannot be longer than {{ limit }} characters'
          allowEmptyString: false