App\Entity\Product:
  attributes:
    id:
      groups: ['product']
    name:
      groups: ['product']
    price:
      groups: ['product']
    currency:
      groups: ['product']
    featured:
      groups: ['product']
    manyToOne:
      category:
        targetEntity: App\Entity\Category
        inversedBy: products
        joinColumn:
          nullable: false
        groups: ['product']